In [ ]:
#check gpu access with pytorch

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
#setup device aganostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#count no of devices
torch.cuda.device_count()

1

In [ ]:
#3.putting tensors(and models ) on the GPU


In [5]:
#create a tensor (deafult on the CPU)
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
#move tensor to GPU if avaible

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#4. moving tensors back to CPU

In [8]:
#if tensor is on GPU , cant transform it to numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
#to fix the GPU tensor with numpy issue , we can first set it to the CPU 

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')